(function() {var implementors = {};
implementors["bzip2"] = [{text:"impl Freeze for <a class=\"struct\" href=\"bzip2/struct.Compress.html\" title=\"struct bzip2::Compress\">Compress</a>",synthetic:true,types:["bzip2::mem::Compress"]},{text:"impl Freeze for <a class=\"struct\" href=\"bzip2/struct.Decompress.html\" title=\"struct bzip2::Decompress\">Decompress</a>",synthetic:true,types:["bzip2::mem::Decompress"]},{text:"impl Freeze for <a class=\"struct\" href=\"bzip2/struct.Compression.html\" title=\"struct bzip2::Compression\">Compression</a>",synthetic:true,types:["bzip2::Compression"]},{text:"impl Freeze for <a class=\"enum\" href=\"bzip2/enum.Action.html\" title=\"enum bzip2::Action\">Action</a>",synthetic:true,types:["bzip2::mem::Action"]},{text:"impl Freeze for <a class=\"enum\" href=\"bzip2/enum.Status.html\" title=\"enum bzip2::Status\">Status</a>",synthetic:true,types:["bzip2::mem::Status"]},{text:"impl Freeze for <a class=\"enum\" href=\"bzip2/enum.Error.html\" title=\"enum bzip2::Error\">Error</a>",synthetic:true,types:["bzip2::mem::Error"]},{text:"impl&lt;R&gt; Freeze for <a class=\"struct\" href=\"bzip2/bufread/struct.BzEncoder.html\" title=\"struct bzip2::bufread::BzEncoder\">BzEncoder</a>&lt;R&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;R: Freeze,&nbsp;</span>",synthetic:true,types:["bzip2::bufread::BzEncoder"]},{text:"impl&lt;R&gt; Freeze for <a class=\"struct\" href=\"bzip2/bufread/struct.BzDecoder.html\" title=\"struct bzip2::bufread::BzDecoder\">BzDecoder</a>&lt;R&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;R: Freeze,&nbsp;</span>",synthetic:true,types:["bzip2::bufread::BzDecoder"]},{text:"impl&lt;R&gt; Freeze for <a class=\"struct\" href=\"bzip2/read/struct.BzEncoder.html\" title=\"struct bzip2::read::BzEncoder\">BzEncoder</a>&lt;R&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;R: Freeze,&nbsp;</span>",synthetic:true,types:["bzip2::read::BzEncoder"]},{text:"impl&lt;R&gt; Freeze for <a class=\"struct\" href=\"bzip2/read/struct.BzDecoder.html\" title=\"struct bzip2::read::BzDecoder\">BzDecoder</a>&lt;R&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;R: Freeze,&nbsp;</span>",synthetic:true,types:["bzip2::read::BzDecoder"]},{text:"impl&lt;W&gt; Freeze for <a class=\"struct\" href=\"bzip2/write/struct.BzEncoder.html\" title=\"struct bzip2::write::BzEncoder\">BzEncoder</a>&lt;W&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;W: Freeze,&nbsp;</span>",synthetic:true,types:["bzip2::write::BzEncoder"]},{text:"impl&lt;W&gt; Freeze for <a class=\"struct\" href=\"bzip2/write/struct.BzDecoder.html\" title=\"struct bzip2::write::BzDecoder\">BzDecoder</a>&lt;W&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;W: Freeze,&nbsp;</span>",synthetic:true,types:["bzip2::write::BzDecoder"]},];
implementors["bzip2_sys"] = [{text:"impl Freeze for <a class=\"struct\" href=\"bzip2_sys/struct.bz_stream.html\" title=\"struct bzip2_sys::bz_stream\">bz_stream</a>",synthetic:true,types:["bzip2_sys::bz_stream"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
